contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #arbor channel"
    url: https://nfcore.slack.com/channels/arbor
    about: Discussion about the tdoerks/arbor pipeline
